version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
  app:
    build: .
    env_file: .env.production
  web:
    extends: app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - neo4j
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/system:/mastodon/public/system
  sidekiq:
    extends: app
    command: bundle exec sidekiq -q default -q mailers
    depends_on:
      - db
      - redis
      - neo4j
    volumes:
      - ./public/system:/mastodon/public/system
