---
en:
  admin:
    dashboard:
      keybase: Keybase integration
    settings:
      enable_keybase:
        desc_html: Allow your users to prove their identity via keybase
        title: Enable keybase integration
      hide_followers_count:
        desc_html: Do not show followers count on user profiles
        title: Hide followers count
      show_reblogs_in_public_timelines:
        desc_html: Show public boosts of public toots in local and public timelines.
        title: Show boosts in public timelines
      show_replies_in_public_timelines:
        desc_html: In addition to public self-replies (threads), show public replies in local and public timelines.
        title: Show replies in public timelines
  generic:
    use_this: Use this
  settings:
    flavours: Flavours
