---
en:
  admin:
    settings:
      captcha:
        desc_html: Configure hCaptcha integration, relying on third-party scripts. This may have security and privacy implications.
        email-confirmation:
          desc_html: Require new users to go through hCaptcha at the e-mail validation step. Bots will not be deterred from creating accounts, but they may be prevented from confirming them, leaving them to be automatically cleaned up after a couple days. This does not interfere with app-based registrations.
          title: CAPTCHA on email validation
        disabled:
          desc_html: Do not require a CAPTCHA
          title: Disabled
        registration-form:
          desc_html: Require new users to go through hCaptcha on the registration form, so that CAPTCHA requirement is immediately apparent to them. This disables app-based registrations and may prevent your instance from being listed as having open registrations.
          title: CAPTCHA on registration forms
        title: CAPTCHA configuration
      enable_keybase:
        desc_html: Allow your users to prove their identity via keybase
        title: Enable keybase integration
      outgoing_spoilers:
        desc_html: When federating toots, add this content warning to toots that do not have one. It is useful if your server is specialized in content other servers might want to have under a Content Warning. Media will also be marked as sensitive.
        title: Content warning for outgoing toots
      hide_followers_count:
        desc_html: Do not show followers count on user profiles
        title: Hide followers count
      show_reblogs_in_public_timelines:
        desc_html: Show public boosts of public toots in local and public timelines.
        title: Show boosts in public timelines
      show_replies_in_public_timelines:
        desc_html: In addition to public self-replies (threads), show public replies in local and public timelines.
        title: Show replies in public timelines
  auth:
    confirm_captcha: User verification
  generic:
    use_this: Use this
  settings:
    flavours: Flavours
