---
fr:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        fields: Vous pouvez avoir jusqu'à %{count} éléments affichés en tant que tableau sur votre profil
        setting_default_content_type_html: Vos posts sont écrits en HTML brut, sauf indication contraire
        setting_default_content_type_markdown: Vos posts utilisent Markdown pour un formatage de texte enrichi, sauf indication contraire
        setting_default_content_type_plain: Vos posts sont écrits en texte brut sans formatage spécial, sauf indication contraire (comportement par défaut de Mastodon)
        setting_default_language: La langue utilisée pour vos posts peut être automatiquement détectée, cependant cette détection n'est pas toujours fiable
