---
zh-CN:
  admin:
    custom_emojis:
      batch_copy_error: 'An error occurred when copying some of the selected emoji: %{message}'
      batch_error: 'An error occurred: %{message}'
    settings:
      captcha_enabled:
        desc_html: This relies on external scripts from hCaptcha, which may be a security and privacy concern. In addition, <strong>this can make the registration process significantly less accessible to some (especially disabled) people</strong>. For these reasons, please consider alternative measures such as approval-based or invite-based registration.<br>Users that have been invited through a limited-use invite will not need to solve a CAPTCHA
        title: Require new users to solve a CAPTCHA to confirm their account
      flavour_and_skin:
        title: Flavour and skin
      hide_followers_count:
        desc_html: 不要在用户资料中显示关注者人数
        title: 隐藏关注者人数
      other:
        preamble: Various glitch-soc settings not fitting in other categories.
        title: Other
      outgoing_spoilers:
        desc_html: 在联邦化嘟文的时候，将这个内容警告添加到没有内容警告的嘟文中。如果你的服务器专用于其他服务器可能希望有内容警告的内容，它会很有用。媒体也将被标记为敏感。
        title: 对外嘟文的内容警告
      show_reblogs_in_public_timelines:
        desc_html: 在本地和跨站时间线中显示公开嘟文的公开转嘟。
        title: 在公共时间线中显示转嘟
      show_replies_in_public_timelines:
        desc_html: 除了公开的自我回复（线程模式），在本地和跨站时间轴中显示公开回复。
        title: 在公共时间轴中显示回复
      trending_status_cw:
        desc_html: When trending posts are enabled, allow posts with Content Warnings to be eligible. Changes to this setting are not retroactive.
        title: Allow posts with Content Warnings to trend
  auth:
    captcha_confirmation:
      hint_html: Just one more step! To confirm your account, this server requires you to solve a CAPTCHA. You can <a href="/about/more">contact the server administrator</a> if you have questions or need assistance with confirming your account.
      title: User verification
  generic:
    use_this: 使用这个
  settings:
    flavours: 风味
